<?php
/**
 * Generated by the WordPress Option Page generator
 * at //jeremyhixon.com/wp-tools/option-page/
 */

class RWMe {
	private $rw_me_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'rw_me_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'rw_me_page_init' ) );
	}

	public function rw_me_add_plugin_page() {
		add_menu_page(
			'RW Me', // page_title
			'RW Me', // menu_title
			'manage_options', // capability
			'rw-me', // menu_slug
			array( $this, 'rw_me_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			100 // position
		);
	}

	public function rw_me_create_admin_page() {
		$this->rw_me_options = get_option( 'rw_me_option_name' ); ?>

		<div class="wrap">
			<h2>RW Me</h2>
			<p>This settings page allows you to manage your contact information in a single location. So that updating it site wide is much easier.</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'rw_me_option_group' );
					do_settings_sections( 'rw-me-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function rw_me_page_init() {
		register_setting(
			'rw_me_option_group', // option_group
			'rw_me_option_name', // option_name
			array( $this, 'rw_me_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'rw_me_setting_section', // id
			'Settings', // title
			array( $this, 'rw_me_section_info' ), // callback
			'rw-me-admin' // page
		);

		add_settings_field(
			'rw_company_name_0', // id
			'Company Name', // title
			array( $this, 'rw_company_name_0_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_contact_name_1', // id
			'Contact Name', // title
			array( $this, 'rw_contact_name_1_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_phone_1_2', // id
			'Phone 1', // title
			array( $this, 'rw_phone_1_2_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_phone_2_3', // id
			'Phone 2', // title
			array( $this, 'rw_phone_2_3_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_toll_free_4', // id
			'Toll Free', // title
			array( $this, 'rw_toll_free_4_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_fax_5', // id
			'Fax', // title
			array( $this, 'rw_fax_5_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_email_6', // id
			'Email', // title
			array( $this, 'rw_email_6_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_address_1_7', // id
			'Address 1', // title
			array( $this, 'rw_address_1_7_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_address_2_8', // id
			'Address 2', // title
			array( $this, 'rw_address_2_8_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_city_9', // id
			'City', // title
			array( $this, 'rw_city_9_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_state_10', // id
			'State', // title
			array( $this, 'rw_state_10_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_state_ab_11', // id
			'State Abbr', // title
			array( $this, 'rw_state_ab_11_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_zip_12', // id
			'Zip Code', // title
			array( $this, 'rw_zip_12_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);

		add_settings_field(
			'rw_country_13', // id
			'Country', // title
			array( $this, 'rw_country_13_callback' ), // callback
			'rw-me-admin', // page
			'rw_me_setting_section' // section
		);
	}

	public function rw_me_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['rw_company_name_0'] ) ) {
			$sanitary_values['rw_company_name_0'] = sanitize_text_field( $input['rw_company_name_0'] );
		}

		if ( isset( $input['rw_contact_name_1'] ) ) {
			$sanitary_values['rw_contact_name_1'] = sanitize_text_field( $input['rw_contact_name_1'] );
		}

		if ( isset( $input['rw_phone_1_2'] ) ) {
			$sanitary_values['rw_phone_1_2'] = sanitize_text_field( $input['rw_phone_1_2'] );
		}

		if ( isset( $input['rw_phone_2_3'] ) ) {
			$sanitary_values['rw_phone_2_3'] = sanitize_text_field( $input['rw_phone_2_3'] );
		}

		if ( isset( $input['rw_toll_free_4'] ) ) {
			$sanitary_values['rw_toll_free_4'] = sanitize_text_field( $input['rw_toll_free_4'] );
		}

		if ( isset( $input['rw_fax_5'] ) ) {
			$sanitary_values['rw_fax_5'] = sanitize_text_field( $input['rw_fax_5'] );
		}

		if ( isset( $input['rw_email_6'] ) ) {
			$sanitary_values['rw_email_6'] = sanitize_text_field( $input['rw_email_6'] );
		}

		if ( isset( $input['rw_address_1_7'] ) ) {
			$sanitary_values['rw_address_1_7'] = sanitize_text_field( $input['rw_address_1_7'] );
		}

		if ( isset( $input['rw_address_2_8'] ) ) {
			$sanitary_values['rw_address_2_8'] = sanitize_text_field( $input['rw_address_2_8'] );
		}

		if ( isset( $input['rw_city_9'] ) ) {
			$sanitary_values['rw_city_9'] = sanitize_text_field( $input['rw_city_9'] );
		}

		if ( isset( $input['rw_state_10'] ) ) {
			$sanitary_values['rw_state_10'] = sanitize_text_field( $input['rw_state_10'] );
		}

		if ( isset( $input['rw_state_ab_11'] ) ) {
			$sanitary_values['rw_state_ab_11'] = sanitize_text_field( $input['rw_state_ab_11'] );
		}

		if ( isset( $input['rw_zip_12'] ) ) {
			$sanitary_values['rw_zip_12'] = sanitize_text_field( $input['rw_zip_12'] );
		}

		if ( isset( $input['rw_country_13'] ) ) {
			$sanitary_values['rw_country_13'] = sanitize_text_field( $input['rw_country_13'] );
		}

		return $sanitary_values;
	}

	public function rw_me_section_info() {
		
	}

	public function rw_company_name_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_company_name_0]" id="rw_company_name_0" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="company"]</code></span>',
			isset( $this->rw_me_options['rw_company_name_0'] ) ? esc_attr( $this->rw_me_options['rw_company_name_0']) : ''
		);
	}

	public function rw_contact_name_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_contact_name_1]" id="rw_contact_name_1" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="contact"]</code></span>',
			isset( $this->rw_me_options['rw_contact_name_1'] ) ? esc_attr( $this->rw_me_options['rw_contact_name_1']) : ''
		);
	}

	public function rw_phone_1_2_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_phone_1_2]" id="rw_phone_1_2" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="phone1"]</code></span>',
			isset( $this->rw_me_options['rw_phone_1_2'] ) ? esc_attr( $this->rw_me_options['rw_phone_1_2']) : ''
		);
	}

	public function rw_phone_2_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_phone_2_3]" id="rw_phone_2_3" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="phone2"]</code></span>',
			isset( $this->rw_me_options['rw_phone_2_3'] ) ? esc_attr( $this->rw_me_options['rw_phone_2_3']) : ''
		);
	}

	public function rw_toll_free_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_toll_free_4]" id="rw_toll_free_4" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="toll-free"]</code></span>',
			isset( $this->rw_me_options['rw_toll_free_4'] ) ? esc_attr( $this->rw_me_options['rw_toll_free_4']) : ''
		);
	}

	public function rw_fax_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_fax_5]" id="rw_fax_5" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="fax"]</code></span>',
			isset( $this->rw_me_options['rw_fax_5'] ) ? esc_attr( $this->rw_me_options['rw_fax_5']) : ''
		);
	}

	public function rw_email_6_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_email_6]" id="rw_email_6" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="email"]</code> or <code>[rw-me show="email-link"]</code></span>',
			isset( $this->rw_me_options['rw_email_6'] ) ? esc_attr( $this->rw_me_options['rw_email_6']) : ''
		);
	}

	public function rw_address_1_7_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_address_1_7]" id="rw_address_1_7" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="address1"]</code></span>',
			isset( $this->rw_me_options['rw_address_1_7'] ) ? esc_attr( $this->rw_me_options['rw_address_1_7']) : ''
		);
	}

	public function rw_address_2_8_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_address_2_8]" id="rw_address_2_8" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="address2"]</code></span>',
			isset( $this->rw_me_options['rw_address_2_8'] ) ? esc_attr( $this->rw_me_options['rw_address_2_8']) : ''
		);
	}

	public function rw_city_9_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_city_9]" id="rw_city_9" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="city"]</code></span>',
			isset( $this->rw_me_options['rw_city_9'] ) ? esc_attr( $this->rw_me_options['rw_city_9']) : ''
		);
	}

	public function rw_state_10_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_state_10]" id="rw_state_10" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="state"]</code></span>',
			isset( $this->rw_me_options['rw_state_10'] ) ? esc_attr( $this->rw_me_options['rw_state_10']) : ''
		);
	}

	public function rw_state_ab_11_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_state_ab_11]" id="rw_state_ab_11" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="state-ab"]</code></span>',
			isset( $this->rw_me_options['rw_state_ab_11'] ) ? esc_attr( $this->rw_me_options['rw_state_ab_11']) : ''
		);
	}

	public function rw_zip_12_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_zip_12]" id="rw_zip_12" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="zip"]</code></span>',
			isset( $this->rw_me_options['rw_zip_12'] ) ? esc_attr( $this->rw_me_options['rw_zip_12']) : ''
		);
	}

	public function rw_country_13_callback() {
		printf(
			'<input class="regular-text" type="text" name="rw_me_option_name[rw_country_13]" id="rw_country_13" value="%s">
			<span style="margin-left: 20px;"><code>[rw-me show="country"]</code></span>',
			isset( $this->rw_me_options['rw_country_13'] ) ? esc_attr( $this->rw_me_options['rw_country_13']) : ''
		);
	}

}
if ( is_admin() )
	$rw_me = new RWMe();

/* 
 * Retrieve this value with:
 * $rw_me_options = get_option( 'rw_me_option_name' ); // Array of All Options
 * $rw_company_name_0 = $rw_me_options['rw_company_name_0']; // rw_company_name
 * $rw_contact_name_1 = $rw_me_options['rw_contact_name_1']; // rw_contact_name
 * $rw_phone_1_2 = $rw_me_options['rw_phone_1_2']; // rw_phone_1
 * $rw_phone_2_3 = $rw_me_options['rw_phone_2_3']; // rw_phone_2
 * $rw_toll_free_4 = $rw_me_options['rw_toll_free_4']; // rw_toll_free
 * $rw_fax_5 = $rw_me_options['rw_fax_5']; // rw_fax
 * $rw_email_6 = $rw_me_options['rw_email_6']; // rw_email
 * $rw_address_1_7 = $rw_me_options['rw_address_1_7']; // rw_address_1
 * $rw_address_2_8 = $rw_me_options['rw_address_2_8']; // rw_address_2
 * $rw_city_9 = $rw_me_options['rw_city_9']; // rw_city
 * $rw_state_10 = $rw_me_options['rw_state_10']; // rw_state
 * $rw_state_ab_11 = $rw_me_options['rw_state_ab_11']; // rw_state_ab
 * $rw_zip_12 = $rw_me_options['rw_zip_12']; // rw_zip
 * $rw_country_13 = $rw_me_options['rw_country_13']; // rw_country
 */




// Client Information Shortcode

function rw_client_info_shortcode($atts) {
    
	$rw_me_options = get_option( 'rw_me_option_name' ); // Array of All Options
	$rw_company_name_0 = $rw_me_options['rw_company_name_0']; // rw_company_name
	$rw_contact_name_1 = $rw_me_options['rw_contact_name_1']; // rw_contact_name
	$rw_phone_1_2 = $rw_me_options['rw_phone_1_2']; // rw_phone_1
	$rw_phone_2_3 = $rw_me_options['rw_phone_2_3']; // rw_phone_2
	$rw_toll_free_4 = $rw_me_options['rw_toll_free_4']; // rw_toll_free
	$rw_fax_5 = $rw_me_options['rw_fax_5']; // rw_fax
	$rw_email_6 = $rw_me_options['rw_email_6']; // rw_email
	$rw_address_1_7 = $rw_me_options['rw_address_1_7']; // rw_address_1
	$rw_address_2_8 = $rw_me_options['rw_address_2_8']; // rw_address_2
	$rw_city_9 = $rw_me_options['rw_city_9']; // rw_city
	$rw_state_10 = $rw_me_options['rw_state_10']; // rw_state
	$rw_state_ab_11 = $rw_me_options['rw_state_ab_11']; // rw_state_ab
	$rw_zip_12 = $rw_me_options['rw_zip_12']; // rw_zip
	$rw_country_13 = $rw_me_options['rw_country_13']; // rw_country
    	
	extract(shortcode_atts(array(
		'show' => '',
        'date' => '',
        'format' => 'ymd',
        'verbose' => ''
	), $atts));
	
	$output = '';
	
	switch (strtolower($show)) { 
		case 'company' :
			$output = $rw_company_name_0;
			break;
        case 'contact' :
			$output = $rw_contact_name_1;
			break;
		case 'phone1' :
			$output = '<a href="tel:' . str_replace('.', '-',$rw_phone_1_2) . '">' . $rw_phone_1_2 . '</a>';
			break;
        case 'phone2' :
			$output = '<a href="tel:' . str_replace('.', '-',$rw_phone_2_3) . '">' . $rw_phone_2_3 . '</a>';
			break;
        case 'toll-free' :
			$output = '<a href="tel:' . str_replace('.', '-',$rw_toll_free_4) . '">' . $rw_toll_free_4 . '</a>';
			break;
        case 'fax' :
			$output = $rw_fax_5;
			break;
        case 'email' :
			$output = $rw_email_6;
			break;
        case 'email-link' :
			$output = '<a href="mailto:' . $rw_email_6 . '">' . $rw_email_6 . '</a>';
			break;
		case 'address1' :
			$output = $rw_address_1_7;
			break;
		case 'address2' :
			$output = $rw_address_2_8;
			break;
		case 'city' :
			$output = $rw_city_9;
			break;
		case 'state' :
			$output = $rw_state_10;
			break;
		case 'state-ab' :
			$output = $rw_state_ab_11;
			break;
		case 'zip' :
			$output = $rw_zip_12;
			break;
		case 'country' :
			$output = $rw_country_13;
            break;
            
        //case 'report-price' :
		//	$output = $rw_report_price;
        //    break;  
        //case 'report-mods' :
		//	$output = $rw_report_mods;
        //    break; 
            
        
        case 'date' :
			$output = rw_me_date($date,$format,$verbose);
			break;
		default :
			$output = $show;
	}

	return $output;

}
add_shortcode( 'rw-me', 'rw_client_info_shortcode' );


/* To Do Examine the Radical Me Plugin and Recreate to Start Own Repo */

function rw_me_date($dateAttr,$format,$verbose){

    $todaysDate = date('Y-m-d',mktime());

    $diff = abs(strtotime($todaysDate) - strtotime($dateAttr));

    $years 			= floor($diff / (365*60*60*24));
    $months 		= floor(($diff - $years * 365*60*60*24) / (30*60*60*24));
    $days 			= floor(($diff - $years * 365*60*60*24 - $months*30*60*60*24)/ (60*60*24));
    $totaldays 		= floor($diff / (60*60*24));
    $totalmonths	= floor($diff / (30*60*60*24));


    $output = '';
    $array = str_split($format);
    foreach ($array as $char) {
        switch($char) {
            case "y" :
                if ($output != '') { $output .=", "; }
                $output .= $years; 
                if ($verbose !='') { $output .= " year" . calc_pluralize($years);}
                break;
            case "m" :
                if ($output != '') { $output .=", "; }
                $output .= $months;
                if ($verbose !='') { $output .= " month" . calc_pluralize($months);}
                break;
            case "d" :
                if ($output != '') { $output .=", "; }
                $output .= $days;
                if ($verbose !='') { $output .= " day" . calc_pluralize($days);}
                break;
            case "D" :
                $output .= $totaldays;
                if ($verbose !='') { $output .= " day" . calc_pluralize($totaldays);}
                break;
            case "M" :
                $output .= $totalmonths;
                if ($verbose !='') { $output .= " month" . calc_pluralize($totalmonths);}
                break;
        }
    }
    return $output;

}

function  calc_pluralize($num, $plural = 's', $single = '') {
    if ($num == 1) return $single; else return $plural;
}

?>